"""rename metadata column to meta_data

Revision ID: 00940bf8dc12
Revises: 3af1e3de0850
Create Date: 2025-04-15 05:57:58.781493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00940bf8dc12'
down_revision: Union[str, None] = '3af1e3de0850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('feedback', sa.Column('template', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('theme', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('template_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'template_id')
    op.drop_column('feedback', 'theme')
    op.drop_column('feedback', 'template')
    op.drop_column('feedback', 'rating')
    # ### end Alembic commands ###
